---
- name: nginx | install
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - nginx
  
- name: nginx | copy config
  sudo: yes
  template: src=nginx.conf dest={{ nginx_conf }}
  notify:
    - nginx | restart
