---
mysql_conf: /etc/mysql/conf.d/encode.cnf

node_nbrew_dir: /usr/local/nodebrew
node_profile: /etc/profile.d/node.sh
node_version: v0.10.32
node_dir: "{{ node_nbrew_dir }}/node/{{ node_version }}"

ruby_rbenv_url: https://github.com/sstephenson/rbenv
ruby_rbenv_path: /usr/local/rbenv
ruby_rbuild_url: https://github.com/sstephenson/ruby-build
ruby_rbuild_path: "{{ ruby_rbenv_path }}/plugins/ruby-build"
ruby_profile: /etc/profile.d/ruby.sh
ruby_version: 2.0.0-p576
ruby_gemrc_path: /etc/gemrc

nginx_conf: /etc/nginx/nginx.conf
