---
- name: ssh | edit sshd config
  sudo: yes
  lineinfile:
    dest: "{{ sshd_conf }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    
  with_items:
    - regexp: ^[#\s]*PermitRootLogin\s
      line: PermitRootLogin no
      
    - regexp: ^[#\s]*PasswordAuthentication\s
      line: PasswordAuthentication no
  
- name: ssh | restart
  sudo: yes
  shell: |
    service ssh restart
  
- name: samba | reload
  sudo: yes
  shell: |
    service samba reload
