---
- name: fstab | install exfat
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - exfat-fuse
    - exfat-utils
  
- name: fstab | mount videos
  sudo: yes
  mount: |
    state=mounted
    name=/media/{{ item.name }}
    src={{ item.src }}
    fstype={{ fstab_video_fstype }}
    opts={{ fstab_video_mount_options }}
  with_items: storages
  
- name: fstab | link current video
  sudo: yes
  file: |
    state=link
    src=/media/{{ current_storage }}
    dest=/media/video
