---
- name: fstab | install exfat
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - exfat-fuse
    - exfat-utils
  
- name: fstab | mount videos
  sudo: yes
  mount: |
    state=mounted
    name={{ item.name }}
    src={{ item.src }}
    fstype={{ fstab_video_fstype }}
    opts={{ fstab_video_mount_options }}
  with_items:
    - {name: /media/video1, src: /dev/sdc1}
    - {name: /media/video2, src: /dev/sdb1}
  
- name: fstab | link current video
  sudo: yes
  file: |
    state=link
    src=/media/video2
    dest=/media/video
