---
- name: reboot | reboot
  sudo: yes
  changed_when: False
  async: 0
  poll: 0
  shell: sleep 2s && shutdown -r now "Reboot by Ansible."
  
- name: reboot | wait for the server to go down
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    state: stopped
  
- name: reboot | wait for the server to come up
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 30
